In [2]:
print('Hello World')

Hello World


In [5]:
tenth=1
type(tenth)

int

In [8]:
a=10
a%10 # modulus
a/10 #float
a//10 #integer

1

In [12]:
name='Aman'
name+1 ##TypeError: can only concatenate str (not "int") to str
name+str(1)

TypeError: can only concatenate str (not "int") to str

In [18]:
first_name="Aman"
last_name="Vishwakarma"
print("The first_name is {} and last_name is {}.".format(first_name,last_name))

The first_name is Aman and last_name is Vishwakarma.


In [ ]:
a=str(input("Enter the name"))
b=str(input("Enter the name"))
print(a ,b)

Aman  Vishwakarma


In [ ]:
class Car:
    def __init__(self,type):
        self.type=type
        

In [1]:
num=int(input("Enter the num"))
if num%2==0:
    print ("The num is even")
else:
    print("The num is Odd")
    

The num is even


In [7]:
marks=int(input("Enter the num"))
if 55<marks<=65:
    print("Grade of Student is :B")
elif 65<marks<=75:
    print("Grade of Student is :A")
elif 75<marks<=85:
    print("Grade of Student is : A+")
elif 85<marks<=100:
    print("Grade of Student is :O")
else:
    print("Grade of Student is : I")


Grade of Student is :A


In [11]:
lst=[1,2,3,4,5,6,7]
even_sum=0
odd_sum=0
for i in lst:
    if i%2==0:
        even_sum=even_sum+i
    else:
        odd_sum=odd_sum+i
print("The even sum is :{}".format(even_sum))
print("The odd sum is :{} ".format(odd_sum))

The even sum is :12
The odd sum is :16 


In [12]:
i=0
even_sum=0
odd_sum=0
while (i<=10):
    if i%2==0:
        even_sum=even_sum+i
    else:
        odd_sum=odd_sum+i
    i=i+1
print(even_sum,odd_sum)

30 25


In [13]:
def word(num):
    a=[]
    for n in num:
        a.append(n*n)
    return a
num=(1,2,3,4,5,6)
x=word(num)
print(x)

[1, 4, 9, 16, 25, 36]


In [23]:
x=1
while(x<8):
    if x==6:
        break
    print(x)
    x=x+1
    

1
2
3
4
5


In [ ]:
x=1
while x<7:
    if x==3:
        continue
    
    print(x)
    x=x+1

1
2
3
4
5


In [ ]:
import math
math.sin(90)

## List

In [3]:
## List is a data structure used in python, that is mutable, changable and denoted as []
lst=[1,2,3,4,'Aman','Vishwakarma']
lst[5]='Sharma'
lst
## List is subscriptable but sets is not.
set_var={"Avengers","Ironman","Spiderman"}
## set_var[2]== It will show error and not subscriptable.We cannot do indexing on sets.

[1, 2, 3, 4, 'Aman', 'Sharma']

## String

In [4]:
## String is a data structure used in python, that are immutable and denoted as "".
Str1="Aman"
Str2="Vishwakarma"



In [6]:
Str1[1]

'm'

In [ ]:
Str2[2]="is"  ## We cannot replace any value at any index in string..


TypeError: 'str' object does not support item assignment

In [34]:
info={
    "Name":"Aman Vishwakarma",
    "Section":"K21UW",
    "Subject":{
        "ML":"A+",
        "DL":"A",
        "NLP":"A",
        "OS":"A"

    }

}
print(info)

{'Name': 'Aman Vishwakarma', 'Section': 'K21UW', 'Subject': {'ML': 'A+', 'DL': 'A', 'NLP': 'A', 'OS': 'A'}}


In [35]:
new_info={"College_Name":"LPU",
          "School":"CSE"}
info.update(new_info)

In [36]:
info

{'Name': 'Aman Vishwakarma',
 'Section': 'K21UW',
 'Subject': {'ML': 'A+', 'DL': 'A', 'NLP': 'A', 'OS': 'A'},
 'College_Name': 'LPU',
 'School': 'CSE'}

In [38]:
info["Subject"]["ML"]

'A+'

In [42]:
info["Group"]=["F.R.I.E.N.D.S"]
info

{'Name': 'Aman Vishwakarma',
 'Section': 'K21UW',
 'Subject': {'ML': 'A+', 'DL': 'A', 'NLP': 'A', 'OS': 'A'},
 'College_Name': 'LPU',
 'School': 'CSE',
 'Group': ['F.R.I.E.N.D.S']}

In [40]:
info.items()

dict_items([('Name', 'Aman Vishwakarma'), ('Section', 'K21UW'), ('Subject', {'ML': 'A+', 'DL': 'A', 'NLP': 'A', 'OS': 'A'}), ('College_Name', 'LPU'), ('School', 'CSE')])

In [23]:
import random
import time
import pyautogui as pg
animal=("Cat","Dog","Mouse")
time.sleep(8)
for i in range(10):
    a=random.choice(animal)
    print("You are a "+a)
    pg.press("Enter")


You are a Dog
You are a Cat
You are a Dog
You are a Mouse
You are a Cat
You are a Mouse
You are a Dog
You are a Mouse
You are a Cat
You are a Dog


## Array


## Array is a data structure that store value of same data type

In [48]:
import numpy as np
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
arr1=np.array([lst1,lst2])



In [50]:
arr1.shape

(2, 5)

In [4]:
import numpy as np
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
arr1=np.array([lst1,lst2])

In [7]:
arr1.shape

(2, 5)

In [12]:
lst=[1,2,3,4,5,6]
lst[:]

[1, 2, 3, 4, 5, 6]

In [20]:
lst[1:4]

[2, 3, 4]

In [23]:
lst[1:]

[2, 3, 4, 5, 6]

In [30]:
lst[1:4]

[2, 3, 4]

In [42]:
import numpy as np
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [43]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [47]:
arr1[2:,2]

array([5])

In [52]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [59]:
arr1[2:,3:4]

array([[6]])

In [60]:
arr1[2:,4]

array([7])

In [62]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [63]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [77]:
arr1[:,::-4]

array([[5, 1],
       [6, 2],
       [7, 3]])

array([[3],
       [4],
       [5]])

In [104]:
np.random.randint(1,40,4).reshape(2,2)

array([[ 2, 35],
       [15, 15]])

## Pandas

if we want to write a script and convert csv file,json files dataset into dataframe then pandas library is used

In [106]:
import pandas as pd
import numpy as np

In [112]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [119]:
df=pd.DataFrame(np.arange(1,21).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1",
                                                                                                 "Column2",
                                                                                                 "Column3",
                                                                                                 "Column4"])
df

Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [123]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000

In [153]:
type(df["Column1"])

pandas.core.series.Series

In [128]:
df[["Column1","Column2","Column3"]]

Column1  Column2  Column3
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [130]:
df.loc["Row1"]

Column1    1
Column2    2
Column3    3
Column4    4
Name: Row1, dtype: int32

In [131]:
df.loc[["Row1","Row2","Row3"]]

Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12

If we select particular Row Or Column then its type would be a "Series", but if we select 2 Row Or 2 Column then it would be a "DataFrame".

In [132]:
df.head()

Column1  Column2  Column3  Column4
Row1        1        2        3        4
Row2        5        6        7        8
Row3        9       10       11       12
Row4       13       14       15       16
Row5       17       18       19       20

In [133]:
df.iloc[2:4,2:]

Column3  Column4
Row3       11       12
Row4       15       16

In [137]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [159]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1",
                                                                                                 "Column2",
                                                                                                 "Column3",
                                                                                                 "Column4"])
df


Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [160]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [161]:
df["Column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [156]:
df.loc["Row1"]

Column1    1
Column2    2
Column3    3
Column4    4
Name: Row1, dtype: int32

In [162]:
df.iloc[:2,:2]

Column1  Column2
Row1        0        1
Row2        4        5

In [163]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

## Can we convert DataFrames into arrays???

##Yes

In [165]:
df.iloc[:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [168]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=["Column1",
                                                                                                 "Column2",
                                                                                                 "Column3"
                                                                                                 ])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4